name: ALKiln tests
on:
  push:
    branches:
      - kiln-tests-lemon
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start isolated server
        id: github_server
        uses: SuffolkLITLab/ALKiln/action_for_github_server@v5
      - name: Run tests
        uses: SuffolkLITLab/ALKiln@v5
        with:
          SERVER_URL: "${{ steps.github_server.outputs.SERVER_URL }}"
          DOCASSEMBLE_DEVELOPER_API_KEY: "${{ steps.github_server.outputs.DOCASSEMBLE_DEVELOPER_API_KEY }}"
